# Generated by Django 6.0.5 on 2026-06-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField(verbose_name='año')),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('capacidad_carga_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kilometraje_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_combustible', models.CharField(choices=[('diesel', 'Diésel'), ('gasolina', 'Gasolina'), ('electrico', 'Eléctrico'), ('gas', 'Gas Natural')], max_length=20)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('mantenimiento', 'En Mantenimiento'), ('fuera_servicio', 'Fuera de Servicio'), ('en_ruta', 'En Ruta')], default='disponible', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'camión',
                'verbose_name_plural': 'camiones',
            },
        ),
    ]
