# Generated by Django 6.0.5 on 2026-06-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='identificador',
            field=models.CharField(help_text='ID interno estandarizado (ej. CAM-001)', max_length=20, null=True, unique=True),
        ),
    ]
