# Generated by Django 6.0.5 on 2026-05-28 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bienes', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bien',
            name='estatus',
            field=models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bien',
            name='identificador',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
